-- AlterTable
ALTER TABLE "Subscription" ADD COLUMN     "end_date" TIMESTAMP(3),
ADD COLUMN     "start_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "renewal_date" DROP NOT NULL;
